version: "3.9"
services:
  migrate:
    build: .
    environment:
      POSTGRES_HOST: "192.168.0.101"
      POSTGRES_PORT: "30001"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"