apiVersion: v1
kind: Secret
metadata:
  name: migrate-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-configmap
data:
  host: "192.168.0.101"
  port: "30001"
  user: "postgres"
  db: "postgres"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: migrate
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: broswen/migrate
        securityContext:
          runAsUser: 65534
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: migrate-secret
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: migrate-configmap
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: migrate-configmap
              key: port
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: migrate-configmap
              key: user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: migrate-configmap
              key: db